### ISSUE TITLE
Planet income not shown when exporting raw materials (no production)

### ISSUE THREAD

**Issue by hellridergit** [calli-eve/eve-pi#5]
Hi, great project!

I had a production setup on a planet and it shown the ISK income on the site fine,
however I decided I'd export raw material elsewhere, and stored the raw materials instead, and the ISK/M does not show anything anymore (column empty).

I checked that the price for it (felsic magma) is correctly returned in a POST call to `https://pi.avanto.tk/api/praisal`.

**Comment by calli-eve** [comment]
Hi! Glad its useful to you :)

Would love to add it, but extractor outputs have been left out for the reason that EVE ESI api does not return real time information on PI. The API updates only when you open the planet view and make changes. This means that we need to do math to get estimates. With factories its pretty simple. They produce X per hour and we can then calculate optimal production yeild and price it.

With extractors its a bit harder. Here is an example of data we get about an extractor:
```
{
      "contents": [],
      "expiry_time": "2024-04-13T13:44:15Z",
      "extractor_details": {
        "cycle_time": 1800,
        "head_radius": 0.015615693293511868,
        "heads": [
          {
            "head_id": 0,
            "latitude": 2.219114065170288,
            "longitude": 5.632610321044922
          },
          {
            "head_id": 1,
            "latitude": 1.9913822412490845,
            "longitude": 5.798852443695068
          },
          {
            "head_id": 2,
            "latitude": 2.230642795562744,
            "longitude": 5.572176933288574
          },
          {
            "head_id": 3,
            "latitude": 2.021350383758545,
            "longitude": 5.786096096038818
          }
        ],
        "product_type_id": 2272,
        "qty_per_cycle": 4694
      },
      "install_time": "2024-04-11T13:44:15Z",
      "last_cycle_start": "2024-04-11T13:44:15Z",
      "latitude": 2.241644859313965,
      "longitude": 5.8136887550354,
      "pin_id": 1043859541809,
      "type_id": 3062
    }
```

There is no average or total to go on. 

In game qty_per_cycle changes also drastically:

<img width="530" alt="image" src="https://github.com/calli-eve/eve-pi/assets/137410303/61f5a035-ad24-493c-b4a6-32d1e32259e9">

That planet goes from 12k to 2k per cycle.  

Graph seems to be something logarithmic, but it changes so much planet to planet depending on extractor positions that I just did not want to guestimate :)

**Comment by hellridergit** [comment]
Got it, totally makes sense. Appreciate elaborated response! :)
