### ISSUE TITLE
Unable to use "Consumed by production chain"

### ISSUE THREAD

**Issue by hellridergit** [calli-eve/eve-pi#8]
Hi.
Attempting to select _Consumed by production chain_ supposedly does not work properly.

**Expected**:
Mark as consumed by production chain

**Actual**:
Does not mark it
Throws a single word `poop` from [this script](https://pi.avanto.tk/_next/static/chunks/671-1e3d87a1c76746b7.js) in the console each time I click the checkbox

Firefox 126 on Win 10 pro [10.0.19045.4412]
Tested without extensions in a private window with the same result.

**Comment by calli-eve** [comment]
Hey! This is a wip feature. I'll try to get it done asap ;)

**Comment by calli-eve** [comment]
https://github.com/calli-eve/eve-pi/commit/9d07ea934c29482d618c55707fd7d229c96b9f61 implemented in this commit
