### ISSUE TITLE
features...

### ISSUE THREAD

**Issue by miki-g** [calli-eve/eve-pi#9]
...is possible to add some features? (if exist in api?)
in planet table add storage values (quantity of sources and products) and actual mining rate of extractor

and in total table - price per unit (?)
and maybe table of all PI prices for comparison (?)

btw. good job this utility
fly safe o7

**Comment by calli-eve** [comment]
Hey! 

Thanks for feedback! I recently explained in this issue: https://github.com/calli-eve/eve-pi/issues/5 why storages and actual rates of extractors are not doable. TLDR: extractors don't show averages or totals via API and storages update only when you expedite or redo routing and submit, like everything else in PI API endpoints.

Price per unit, and PI price comparison per unit could be a nice feature that ill put on todo list. I myself use this nice tool for comparing what to setup: https://www.adam4eve.eu/pi_rank.php

Calli
